services:
  backend:
    build:
      context: ./RevibeFit-Backend
      target: deps
    command: sh -c "npm install && npx nodemon src/index.js"
    environment:
      NODE_ENV: development
    volumes:
      - ./RevibeFit-Backend/src:/app/src
      - ./RevibeFit-Backend/package.json:/app/package.json

  frontend:
    build:
      context: ./RevibeFit-Frontend
      target: builder
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ./RevibeFit-Frontend/src:/app/src
      - ./RevibeFit-Frontend/index.html:/app/index.html
      - ./RevibeFit-Frontend/vite.config.js:/app/vite.config.js
      - ./RevibeFit-Frontend/package.json:/app/package.json
