import { generateAllMonthlyInvoices } from "../services/invoiceService.js";
import { sendNotification } from "../services/notificationService.js";
import { PlatformInvoice } from "../models/platformInvoice.model.js";
import { NOTIFICATION_TYPES, NOTIFICATION_CHANNELS } from "../constants.js";

/**
 * Auto-generate monthly invoices for all lab partners.
 * Runs on the 1st of every month for the previous month.
 */
export const generateAllMonthlyInvoicesJob = async () => {
  const now = new Date();
  // Generate for previous month
  const targetMonth = now.getMonth() === 0 ? 12 : now.getMonth();
  const targetYear = now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear();

  console.log(`[CRON] Generating invoices for ${targetMonth}/${targetYear}...`);

  try {
    const results = await generateAllMonthlyInvoices(targetMonth, targetYear);
    console.log(`[CRON] Invoice generation complete:`, results);

    // Send notifications for newly generated invoices
    if (results.generated > 0) {
      const newInvoices = await PlatformInvoice.find({
        "billingPeriod.month": targetMonth,
        "billingPeriod.year": targetYear,
        autoGenerated: true,
      }).select("labPartnerId invoiceNumber totalCommission gstDetails dueDate");

      for (const invoice of newInvoices) {
        try {
          await sendNotification({
            userId: invoice.labPartnerId,
            type: NOTIFICATION_TYPES.INVOICE_GENERATED,
            title: "Monthly Invoice Generated",
            message: `Your invoice ${invoice.invoiceNumber} for ₹${invoice.gstDetails?.totalInvoiceAmount?.toLocaleString("en-IN") || invoice.totalCommission.toLocaleString("en-IN")} has been generated. Due by ${invoice.dueDate.toLocaleDateString("en-IN")}.`,
            data: {
              invoiceId: invoice._id,
              invoiceNumber: invoice.invoiceNumber,
              amount: invoice.gstDetails?.totalInvoiceAmount || invoice.totalCommission,
              dueDate: invoice.dueDate,
            },
            channels: [
              NOTIFICATION_CHANNELS.IN_APP,
              NOTIFICATION_CHANNELS.EMAIL,
            ],
          });
        } catch (error) {
          console.error(`[CRON] Notification failed for invoice ${invoice.invoiceNumber}:`, error.message);
        }
      }
    }
  } catch (error) {
    console.error("[CRON] Invoice generation job failed:", error.message);
  }
};
