import mongoose from "mongoose";
import { INVOICE_STATUSES, GST_TYPES } from "../constants.js";

const platformInvoiceSchema = new mongoose.Schema(
  {
    labPartnerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: [true, "Lab partner ID is required"],
      index: true,
    },
    invoiceNumber: {
      type: String,
      required: [true, "Invoice number is required"],
      unique: true,
      index: true,
    },
    billingPeriod: {
      month: { type: Number, min: 1, max: 12 },
      year: { type: Number, min: 2020 },
      startDate: { type: Date },
      endDate: { type: Date },
      type: {
        type: String,
        enum: ["monthly", "weekly", "custom"],
        default: "monthly",
      },
    },

    // Financial details
    totalCommission: {
      type: Number,
      required: [true, "Total commission is required"],
      min: [0, "Total commission cannot be negative"],
    },
    numberOfBookings: {
      type: Number,
      required: [true, "Number of bookings is required"],
      min: 0,
      default: 0,
    },
    totalBookingValue: {
      type: Number,
      required: [true, "Total booking value is required"],
      min: 0,
      default: 0,
    },
    commissionRate: {
      type: Number,
      required: [true, "Commission rate is required"],
      default: 10,
      min: 0,
      max: 100,
    },
    // Net settlement amount paid out to the lab partner
    totalSettlementAmount: {
      type: Number,
      default: 0,
      min: 0,
    },

    // GST details (B2B tax invoice compliance)
    gstDetails: {
      platformGstin: { type: String, default: "" },
      labPartnerGstin: { type: String, default: "" },
      placeOfSupply: { type: String, default: "" },
      sacCode: { type: String, default: "999316" },
      taxType: {
        type: String,
        enum: [...Object.values(GST_TYPES), null],
        default: null,
      },
      taxableValue: { type: Number, default: 0, min: 0 },
      cgstRate: { type: Number, default: 0 },
      cgstAmount: { type: Number, default: 0 },
      sgstRate: { type: Number, default: 0 },
      sgstAmount: { type: Number, default: 0 },
      igstRate: { type: Number, default: 0 },
      igstAmount: { type: Number, default: 0 },
      totalTaxAmount: { type: Number, default: 0 },
      totalInvoiceAmount: { type: Number, default: 0 }, // commission + tax
    },

    // Invoice status and dates
    status: {
      type: String,
      enum: [
        ...Object.values(INVOICE_STATUSES),
        // Keep legacy status for backward compat
        "payment_due",
      ],
      default: INVOICE_STATUSES.ISSUED,
      index: true,
    },
    dueDate: {
      type: Date,
      required: [true, "Due date is required"],
      index: true,
    },
    gracePeriodEnd: {
      type: Date,
      default: null,
    },
    generatedDate: {
      type: Date,
      default: Date.now,
      required: true,
    },
    paidDate: { type: Date, default: null },

    // Payment details
    paymentMethod: {
      type: String,
      enum: ["bank_transfer", "online", "cash", "cheque", null],
      default: null,
    },
    paymentReference: { type: String, default: null },
    paymentNotes: { type: String, default: null },

    // Related bookings
    bookingIds: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "LabBooking",
      },
    ],

    // Settlement references (new platform-mediated flow)
    settlementIds: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Settlement",
      },
    ],

    // Commission breakdown - detailed list of each booking's commission
    commissionBreakdown: [
      {
        bookingId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "LabBooking",
        },
        settlementId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "Settlement",
          default: null,
        },
        fitnessEnthusiastId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "User",
        },
        fitnessEnthusiastName: String,
        testNames: [String],
        bookingDate: Date,
        totalAmount: Number,
        commissionAmount: Number,
        commissionRate: Number,
        gstAmount: { type: Number, default: 0 },
        netSettlement: { type: Number, default: 0 },
      },
    ],

    // PDF
    pdfPath: { type: String, default: null },
    pdfGeneratedAt: { type: Date, default: null },

    // Reminder tracking
    reminders: [
      {
        type: {
          type: String,
          enum: ["pre_due", "on_due", "grace_warning", "grace_final"],
        },
        sentAt: Date,
        channel: {
          type: String,
          enum: ["email", "sms", "in_app"],
        },
      },
    ],

    // Generation metadata
    autoGenerated: { type: Boolean, default: true },
    generatedBy: {
      type: String,
      default: "system",
    },

    // Invoice request tracking (lab partner can request early invoice)
    requestedByLabPartner: { type: Boolean, default: false },
    requestedDate: { type: Date, default: null },
    requestNotes: { type: String, default: null },

    notes: { type: String, trim: true },
  },
  { timestamps: true }
);

// Indexes
platformInvoiceSchema.index({
  labPartnerId: 1,
  "billingPeriod.year": 1,
  "billingPeriod.month": 1,
});
platformInvoiceSchema.index({
  labPartnerId: 1,
  "billingPeriod.startDate": 1,
  "billingPeriod.endDate": 1,
});
platformInvoiceSchema.index({ status: 1, dueDate: 1 });

// Virtual: formatted billing period
platformInvoiceSchema.virtual("formattedBillingPeriod").get(function () {
  const months = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
  ];
  return `${months[this.billingPeriod.month - 1]} ${this.billingPeriod.year}`;
});

// Method: check if invoice is overdue
platformInvoiceSchema.methods.isOverdue = function () {
  const overdueStatuses = [INVOICE_STATUSES.ISSUED, "payment_due"];
  return overdueStatuses.includes(this.status) && new Date() > this.dueDate;
};

// Method: check if still in grace period
platformInvoiceSchema.methods.isInGracePeriod = function () {
  if (!this.gracePeriodEnd) return false;
  const now = new Date();
  return now > this.dueDate && now <= this.gracePeriodEnd;
};

// Pre-save hook: auto-update overdue status
platformInvoiceSchema.pre("save", function (next) {
  const activeStatuses = [INVOICE_STATUSES.ISSUED, "payment_due"];
  if (activeStatuses.includes(this.status) && new Date() > this.dueDate) {
    this.status = INVOICE_STATUSES.OVERDUE;
  }
  next();
});

export const PlatformInvoice = mongoose.model(
  "PlatformInvoice",
  platformInvoiceSchema
);
